# Generated by Django 4.1.1 on 2022-09-29 13:23

from django.db import migrations, models
import django.db.models.deletion
import todos.utils.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('in-progress', 'INPROGRESS'), ('done', 'DONE'), ('archived', 'ARCHIVED')], default=todos.utils.enums.ProjectStatus['DRAFT'], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.project')),
            ],
        ),
    ]
